### PR TITLE
Update quick_operators.py

### PR DESCRIPTION
**Pull request by zeffii**
even if you don't accept the suggestions, hopefully you will see there are less verbose ways to invert a False/True.

### CODE REVIEW

**Comment by zeffii** [comment]
https://gist.github.com/zeffii/5659108   ( small edits )

yeah,  run this in the blender text editor

```
    damaja = False
    damaja = not damaja
    print(damaja)
```

**Comment by zeffii** [comment]
Also, there are a few functions that could be combined, like sculptAxisLock and sculptSymmetry. I hadn't run the previous pull request, it was purely optical refactoring (not generally a great idea, but it can be cathartic and a fine way to start )

**Comment by carter2422** [comment]
@zeffii ah now I follow the "not" method. That's very cool, I like it! 

I've been meaning to combine the sculpt symmetry and axis lock operators but haven't gotten around to it yet. Thanks for the reminder. I've added it to my to-do list.

**Comment by carter2422** [comment]
I'm having a bit of trouble combining the symmetry operators into a single class. I'm using a string property and feel like I'm close but it's not quite there. Would you be willing to take a look?

Here is my new class:

``` python
class sculptSymmetry(bpy.types.Operator):
    """Toggle Symmetry For Sculpting"""
    bl_idname = "sculpt.symmetry"
    bl_label = "Toggle Sculpt Symmetry"

    axis = bpy.props.StringProperty()

    def execute(self, context):
        symmetry = self.axis
        self.axis = not symmetry
```

And here is the menu entry (inside a draw function obviously):

``` python
xSymmetry = layout.operator("sculpt.symmetry", "X Symmetry")
xSymmetry.axis = context.tool_settings.sculpt.use_symmetry_x
```

**Comment by zeffii** [comment]
i would use an IntProperty with the options -1, 0 and 1 .
perhaps looks at the end of this script for some inspiration :
https://github.com/zeffii/rawr/blob/master/blender/scripts/addons_contrib/mesh_edge_intersection_tools.py

In your shoes I would break this out into a temporary testing .py with the
boilerplate etc and a mock bl_info so you can keep it small and testable.
then once you are happy re-integrate into the existing .py

it's kind of my bedtime rightnow.

**Comment by carter2422** [comment]
Ah that is just what I needed. Thanks! It took be a bit to work out the keymaps and such but I came up with this: https://github.com/CGCookie/script-bakery/commit/95fbb0f52034b605a3be9f1a020fce3ed11411bd

**Comment by zeffii** [comment]
_Disco!_ This stuff certainly isn't always obvious. Combining those makes it easier to maintain and read (for fresh eyes, or eyes returning after months). A useful idiom for when you might otherwise have multiple operators that perform almost identical state changes.  

I'll do another pull request when time permits.

**Comment by zeffii** [comment]
I used the term 'boilerplate' incorrectly last night in one comment . Think of boilerplate as _everything_ that needs to be constructed around the functional parts of addons. ( license, bl_info, register/unregister ) to get Blender to recognize it as an addon. One might argue that the license isn't strictly part of the boilerplate, but it's certainly a requirement for inclusion in the Blender code base. 

In the case of the class register / unregister that convenience method `bpy.utils.register_module(__name__)` at least helps the boilerplate ( in terms of lines of code ) shrink.

**Pull request closed without merging**
